### ISSUE TITLE
Add admin-ui register_admin_ui errand to pipeline

### ISSUE THREAD

**Issue by ghost** [18F/cg-atlas#103]
In order to have the admin-ui deployment fully automated, as SREs we need to add the `register_admin_ui` bosh errand to the concourse pipeline in `cg-deploy-admin-ui`.
## Acceptance Criteria
- [ ] The `register_admin_ui` bosh errand is run after each admin-ui deployment.

**Comment by ghost** [comment]
Thanks to @LinuxBozo for pointing out errand examples:

"See the cg-pipelines task to enable running errands.. see cg-deploy-logsearch pipeline for example usage.. the push-kibana job"

"also, same thing is in cg-deploy-cf for running the smoke/acceptance tests"

**Comment by ghost** [comment]
And great input from @sharms:

https://github.com/18F/cg-deploy-logsearch/blob/master/pipeline.yml#L63-L71

you can literally just take that, and rename it

**Comment by sharms** [comment]
https://github.com/18F/cg-deploy-admin-ui/pull/14
