### ISSUE TITLE
Monitor elastic cluster health

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-atlas#108]
We should get paged when the elastic cluster health is red or yellow. Riemann has an elastic monitoring tool that could be helpful: https://github.com/riemann/riemann-tools/blob/master/tools/riemann-elasticsearch/bin/riemann-elasticsearch

cc @dlapiduz @sharms @LinuxBozo

**Comment by mogul** [comment]
Already demo'd as working in production.
