### ISSUE TITLE
Fix cg-aws-light-stemcell-builder

### ISSUE THREAD

**Issue by ghost** [18F/cg-atlas#109]
This process/pipeline is broken.  Builds are failing due to a file glob issue and we also need to remove the conversion to vmdk step that was also removed upstream in https://github.com/cloudfoundry-incubator/aws-light-stemcell-builder/commit/59ac7f7651d5db04b10edf8233dc8fa0abf04629.
- [x] Remove the conversion to vmdk
- [x] General fixes and cleanup

**Comment by ghost** [comment]
Related to #105

**Comment by ghost** [comment]
https://github.com/18F/cg-aws-light-stemcell-builder/pull/4

**Comment by mogul** [comment]
@dlapiduz we're doing work to ensure this is a lighter fork to maintain, but can you verify that it works and can be closed?

**Comment by mogul** [comment]
Confirmed working.
