### ISSUE TITLE
Ship host logs to common destination

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#11]
In order to meet logging requirements for FedRAMP, we want host logs from all VMs to be shipped&nbsp;to a common destination.

Acceptance Criteria
- [x] When a new VM is added, logs from that host become&nbsp;visible in the common repository
- [x] Bosh release for 'awslogs' 
- [x] CI Pipeline to automatically update awslogs release
- [x] Metrics are sent to CloudWatch

**Comment by mogul** [comment]
[Potentially useful/relevant](http://www.haydonryan.com/configure-pivotal-cloud-foundry-1-4-for-aws-to-export-logs-to-cloudwatch-logs/)

**Comment by mogul** [comment]
Refer also to [the card on the SecOps board](https://trello.com/c/0lwpNXzL/72-cloudtrail-logs-need-to-be-made-available-to-gsa-secops)

**Comment by sharms** [comment]
Creating bosh release called 'awslogs'

**Comment by sharms** [comment]
Repo is at: https://github.com/18F/cg-awslogs-boshrelease
Pipeline is at: http://ci.cloud.gov/pipelines/awslogs-boshrelease
