### ISSUE TITLE
Aggregate platform logs

### ISSUE THREAD

**Issue by ghost** [18F/cg-atlas#111]
As an SRE, I should be able to utilize aggregated platform logs in a system such as ELK.
## Acceptance Criteria
- [ ] CF component logs are sent to ELK via `syslog_daemon_config`

**Comment by mogul** [comment]
We're going to wait on this until we can say that our logsearch ELK is stable and HA.

**Comment by dlapiduz** [comment]
@sushiandbeer @jmcarp can we close this?
