### ISSUE TITLE
Integration test: Are logs coming through?

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-atlas#113]
As an SRE, I want to be paged when logs.cloud.gov stops receiving logs for any reason.

Note: this is one of the proposed countermeasures from the retro on the recent logs.cloud.gov outage.
## Implementation sketch
- https://gist.github.com/jmcarp/625cca3bb454409e3c6f9be97746f24f
- https://github.com/18F/cg-riemann-boshrelease/pull/9

**Comment by mogul** [comment]
Already demo'd as working in production.
