### ISSUE TITLE
Common releases jobs need to exist for Master bosh

### ISSUE THREAD

**Issue by rogeruiz** [18F/cg-atlas#117]
The following releases all need to be uploaded to Master bosh in order for Tooling bosh to be deployed.
- [ ] fisma (cg-hardening)
- [ ] tripwire
- [ ] awslogs
- [ ] nessus-agent
- [ ] newrelic
- [ ] riemannc
- [ ] clamav
- [ ] snort

Discovered during #62

**Comment by mogul** [comment]
Josh says this is all done now.
