### ISSUE TITLE
Encrypt Cloud Controller Blobstores

### ISSUE THREAD

**Issue by sharms** [18F/cg-atlas#122]
In order to provide end to end encrypted infrastructure the Cloud Controller Droplets / Blobstores should be encrypted

Acceptance Criteria:
- [ ] cc-\* resources show they are encrypted via AES256 in Amazon S3 Console

Related:
- https://github.com/18F/cg-deploy-cf/pull/93

**Comment by sharms** [comment]
Closed by https://github.com/18F/cg-deploy-cf/commit/0fc02ae4cc593431d8eee93a6b8c2328099a4748

**Comment by dlapiduz** [comment]
Cool! didn't know this was an option!

**Comment by rogeruiz** [comment]
@sharms can you pop in the screenshot?
