### ISSUE TITLE
Reject S3 uploads without server-side encryption

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-atlas#123]
Buckets that must be encrypted should reject uploads that don't specify server-side encryption. Example policy: http://s3tools.org/kb/item11.htm
- [ ] Blobstores
- [x] Platform (buildpacks, droplets, etc)
- [ ] Buckets managed by concourse (stemcell, bosh releases)
- [ ] Secrets buckets (cloud-gov-varz, concourse-credentials)
- [ ] Terraform state

**Comment by jmcarp** [comment]
https://github.com/18F/cg-provision/pull/46

**Comment by jmcarp** [comment]
Bucket policies are set correctly, and uploads without sse are rejected:

![screen shot 2016-07-20 at 5 46 48 pm](https://cloud.githubusercontent.com/assets/1633460/17004576/94bca32c-4ea3-11e6-967a-87ce220361a6.png)
<img width="710" alt="screen shot 2016-07-20 at 5 55 30 pm" src="https://cloud.githubusercontent.com/assets/1633460/17004584/9a60a22e-4ea3-11e6-92c8-a3e95261bef2.png">

**Comment by rogeruiz** [comment]
👍
