### ISSUE TITLE
Fix EW Staging / Prod and Update Stemcells

### ISSUE THREAD

**Issue by sharms** [18F/cg-atlas#126]
Current staging environment broken since 17 days ago without any new working deploys.  In order to test that release and features are at parity with GovCloud, we need these pipelines to work.
- [ ] Legacy cloud.gov deployment successfully deploys

**Comment by sharms** [comment]
Blocked on https://github.com/18F/cg-deploy-cf/pull/99

**Comment by sharms** [comment]
Also needs https://github.com/18F/cg-deploy-cf/pull/101

**Comment by sharms** [comment]
Waiting for https://github.com/18F/cg-atlas/issues/127

**Comment by rogeruiz** [comment]
Let's make a research story around fixing the URL naming issue we discovered on this task.

**Comment by sharms** [comment]
https://github.com/18F/cg-atlas/issues/133
