### ISSUE TITLE
Uncomment terraform bucket provisioning steps after upstream changes are merged

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-atlas#128]
We added a handful of commented-out bucket provisioning steps in https://github.com/18F/cg-provision/pull/46 that can be uncommented once bosh and s3-resource accept and release some of our pull requests:
- https://github.com/concourse/s3-resource/pull/43 (waiting for merge and release)
- https://github.com/cloudfoundry/bosh/commit/d473e74ccf9df32e2b38cef0ff40ce1616a3195b (waiting for release)

Commented steps live in https://github.com/18F/cg-provision/blob/master/terraform/modules/bootstrap_buckets/buckets.tf#L22-L56.

**Comment by LinuxBozo** [comment]
@jmcarp We can proceed with these now, yeah?
