### ISSUE TITLE
Update logsearch and logsearch-for-cloudfoundry

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-atlas#131]
- [ ] Use a current release of logsearch-boshrelease (see https://github.com/18F/cg-deploy-logsearch/pull/20)
- [ ] Switch to logsearch-for-cloudfoundry [upstream](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry) or pull in upstream changes

**Comment by jmcarp** [comment]
@LinuxBozo: how dangerous would it be to upgrade logsearch-boshrelease to latest on govcloud and see what happens? We're >250 commits behind the latest release, but the release notes after v200 (which we're on now) don't mention breaking changes, and the version bumps to ELK components are all minor/patch--although there's a note about upgrading to logstash 2.2 here: https://www.elastic.co/guide/en/logstash/current/upgrading-logstash-2.2.html.

**Comment by mogul** [comment]
Josh is testing a deploy of the upstream. The deploy worked, but it's not gathering logs yet, so needs debugging. We're looking to resolve this so we can stay in tandem with upstream.

**Comment by mogul** [comment]
Now ingesting logs, kibana dashboards are up, but the collected logs aren't showing in the dashboards, so still need to resolve that.  Nearly done.

**Comment by jmcarp** [comment]
Sent a few mostly small patches upstream:
- https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/145
- https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/148
- https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/149
- https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/152
- https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/153

**Comment by mogul** [comment]
Just rolled out a new version incorporating pretty much everything enumerated above
