### ISSUE TITLE
Research: Fix East Naming Issues

### ISSUE THREAD

**Issue by sharms** [18F/cg-atlas#133]
Currently US East is named incorrectly which will cause issues with all restarts and deployments

The following still work or are renamed:
- [x] www & `null` (a.k.a cloud.gov)
- [x] docs
- [x] compliance
- [x] logs
- [x] invite
- [x] dashboard

Constraints:
- CloudFront is not available in GovCloud
- Tested docs-fix.cloud.gov which when used via CNAME ends up returning *.sys.cloud.gov certificate

**Comment by sharms** [comment]
<img width="540" alt="screen shot 2016-07-25 at 4 00 42 pm" src="https://cloud.githubusercontent.com/assets/95657/17115364/0197b064-5281-11e6-9e1d-87a53dc8cfec.png">

**Comment by mogul** [comment]
Update from Diego: Seems like the only quick way to do this is with CloudFront, though it's not available in GovCloud. We will likely use it anyway, as we do Route53, and not consider it within our boundary. Adam: Could also have our own proxy layer behind ELBs... but it's more work. Bret: We'll need to do that eventually anyway for EINSTEIN-type stuff... but not ready to do that yet and it's more work than is worth doing to resolve this today.

Resolved: Go the CloudFront route.

**Comment by dlapiduz** [comment]
@sharms I am going to edit the list to make sure we only have the ones we care about

**Comment by dlapiduz** [comment]
also a note about this, please lets create the cloudfront distros using the govcloud cdn broker not the e/w one. That way we have them ready in the new env.

**Comment by jmcarp** [comment]
Update:
- The www, compliance, and docs domains moved to cloudfront, with service instances provisioned in govcloud / cloud-gov / services
- The logs, invite, and dashboard domains were moved to custom domains in east/west
- The cloud.gov domain was deleted from east/west

AFAICT, we should be able to close this issue and redeploy east/west.

**Comment by dlapiduz** [comment]
@jmcarp can we close this?
