### ISSUE TITLE
Detect and alert on signs of host attack

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#14]
In order to be aware when someone is attacking our platform from a nearby host, we want common signs of&nbsp;attack across eth0 in our hosts to result in alerts.

**Acceptance Criteria**
- [x] A network IDS&nbsp;is deployed on all hosts and paying attention to eth0
- [x] The network IDS signatures used to detect attacks are updated regularly, with trivial team effort
- [x] When attacks are detected, alerts are sent via Riemann and PagerDuty

**Implementation Sketch**
- Use Bosh release for Snort

*\* Releases
- [x] cg-deploy-monitoring
- [x] cg-deploy-concourse https://github.com/18F/cg-deploy-concourse/pull/17 @rogeruiz
- [x] cg-deploy-admin-ui https://github.com/18F/cg-deploy-admin-ui/pull/11 @rogeruiz
- [x] cg-deploy-cf https://github.com/18F/cg-deploy-cf/pull/91 @rogeruiz
- [x] cg-deploy-logsearch https://github.com/18F/cg-deploy-logsearch/pull/8 @rogeruiz

**Comment by mogul** [comment]
Working but incomplete bosh release done, cron updates to rules and alerts yet to do.

**Comment by jmcarp** [comment]
Based on conversation with @sharms and @frsfx:
- [ ] Write a concourse resource for snort rules
- [ ] Add job to https://ci.fr.cloud.gov/pipelines/deploy-bosh to fetch rules and cut new bosh releases

**Comment by jmcarp** [comment]
Here's an alert!

<img width="726" alt="screen shot 2016-06-29 at 1 13 45 pm" src="https://cloud.githubusercontent.com/assets/1633460/16461728/f2b6e5e0-3dfb-11e6-8ceb-e0c9e4609051.png">

**Comment by rogeruiz** [comment]
I went ahead and merged those PRs in @jmcarp. I'll move this into Awaiting Acceptance as I watch Concourse turn green 🍏 .

**Comment by mogul** [comment]
We will pick a rule that Snort should alert on, and use that to demo that this works, and for the sprint review. (Diego thinks this will make a good tech talk too.)
