### ISSUE TITLE
Evaluate kubernetes for managed services

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-atlas#141]
Implementation sketch:
- https://github.com/CloudCredo/kubernetes-release
- https://github.com/trustedanalytics/kubernetes-broker

Tasks:
- [x] Update k8s-release to current etcd, docker, k8s
- [x] Deploy k8s-release to staging
- [x] Deploy k8s-broker to staging

**Comment by mogul** [comment]
Can you give an update as to how this work is going? It looks like a research story, but there's no timebox on it, and it's hard to see what other backlog work is implied.

**Comment by mogul** [comment]
Long since done.
