### ISSUE TITLE
Raise ELB limit on govcloud

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-atlas#146]
Our in-progress kubernetes service broker exposes kubernetes services outside the cluster using dynamically provisioned ELBs. For this to work, we need to be able to provision lots of ELBs (one per service), but AWS imposes a limit of 20 ELBs by default. This limit needs to be raised, or ideally removed. @sharms and I didn't see a way to do this via the console--I didn't see the ELB limit listed under the "limits" panel under ec2, and the links for other services in that panel don't seem to work on govcloud anyway (they just link to east-west). @dlapiduz @LinuxBozo: do you know how to do this?

**Comment by dlapiduz** [comment]
the limit is increased!

**Comment by dlapiduz** [comment]
(to 50)
