### ISSUE TITLE
Authenticate Concourse against in-boundary IDP

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#147]
In order to ensure that people outside of the cloud.gov team cannot grant or gain administrator access to our deployment, we want Concourse to refer to an in-boundary MFA-enabled IDP for authn+authz rather than GitHub teams.

**Acceptance criteria**
- [ ] cloud.gov operational systems refer to an in-boundary IDP for authn+authz, rather than GitHub
- [ ] We have a documented process for how people gain/lose access via our IDP

**Implementation sketch**

**Comment by mogul** [comment]
Note [this PR](https://github.com/concourse/atc/pull/101) which makes Concourse work with generic OAuth providers, not just GitHub.

**Comment by mogul** [comment]
Note also that the switchover should coincide with development of a formal process for gaining access.

**Comment by dlapiduz** [comment]
I created a request but we need to create an endpoint for admin uaa.

**Comment by brittag** [comment]
Ideally there should be some sort of auditable log of access requests, creations, removals, etc., like for other types of privileged access.

**Comment by LinuxBozo** [comment]
UAA on tooling BOSH updated, and fronted with an ELB just for UAA access.
uaa: https://opauaa.fr.cloud.gov
login: https://opslogin.fr.cloud.gov
saml metadata: https://opslogin.fr.cloud.gov/saml/metadata

Things to note currently:
- Accounts will not be auto-created by saml, but as needed.
- Formal procedures need to be written on how to create and associate account with idp.
- Waiting on GSA for integration into SecureAuth

**Comment by mogul** [comment]
Marking blocked based on the GSA dependency

**Comment by LinuxBozo** [comment]
Integrated now with SecureAuth.
Still waiting on https://github.com/concourse/concourse/pull/658 for ability to authorize by scope.

**Comment by mogul** [comment]
Leave it blocked for that reason, then?

**Comment by LinuxBozo** [comment]
Blocked on waiting on newest Grafana release so we can migrate metrics to using UAA over github. 

We have a current workaround for Concourse/scope issue by just not auto-creating shadow accounts in UAA. Script for creating accounts: https://github.com/18F/cg-scripts/blob/master/make-ops-admin.sh
Documentation updated: https://docs.cloud.gov/ops/managing-users/#managing-admins

**Comment by LinuxBozo** [comment]
Splitting out metrics so this can be closed..
