### ISSUE TITLE
Detect and alert on signs of host compromise

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#15]
In order to be aware when someone has established foothold on a&nbsp;host, we want common signs of rootkits or other malware on a host to result in alerts.
### Acceptance Criteria
- [x] Local host-IDS (HIDS) is deployed on all hosts GovCloud
- [x] The HIDS signatures used to detect attacks are updated regularly, with trivial team effort
- [x] When attacks are detected, alerts are sent via Riemann and PagerDuty
### Implementation Sketch

Fork and update the EMC clamav boshrelease to use the most current version of clamav and be built using our boshrelease pipeline: https://github.com/18F/cg-clamav-boshrelease.  Ensure `LogSyslog` is set to true in the clamav config and @sharms's magic will do the rest.

**Comment by mogul** [comment]
Client release under development, per stand-up today, but blocked by the staging issues identified under #6.

**Comment by mogul** [comment]
Just to check: This one's about having something to find rootkits, etc. so `rkhunter` or `clamav`. My understanding is that right now we're working on Tripwire, which is in #13 ... So I'm moving this one back to the backlog and moving that one forward.

**Comment by cnelson** [comment]
Is a bosh release for `clamav` that's configured to scan on file access and running freshclam to keep the database updated enough for this story?

Where's the documentation on how applications get data into  your riemann -> pagerduty setup for the last AC?

**Comment by sharms** [comment]
clamav will be sufficient for now at the level we are certifying.  In order to pipe this into Riemann we should log to syslog and filter in Riemann - https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/configuring-destinations-riemann.html

I will escalate the alerts to pagerduty once I see those events come in

**Comment by mogul** [comment]
Should we be documenting this pattern generally as part of our docs?

**Comment by mogul** [comment]
Confirmed alerts going through Riemann, will roll out as deployments happen.
