### ISSUE TITLE
Update systems to 3262.12

### ISSUE THREAD

**Issue by sharms** [18F/cg-atlas#160]
In order to close security vulnerabilities identified 2016/09/13, we need to deploy a newer Stemcell:
- [x] Legacy EC2 CloudFoundry
- [x] Legacy EC2 Monitoring
- [x] Legacy EC2 Logsearch
- [x] Legacy EC2 Concourse
- [x] Legacy EC2 Admin UI
- [x] Concourse-AMI
- [x] Concourse 18F Task Image
- [x] Nessus Manager
- [x] GovCloud EC2 CloudFoundry
- [x] GovCloud EC2 Monitoring
- [x] GovCloud EC2 Logsearch
- [x] GovCloud EC2 Concourse
- [x] GovCloud EC2 Admin UI
- [x] GovCloud EC2 Diego

**Comment by mogul** [comment]
Already done and onto the next version.
