### ISSUE TITLE
Deprecate wercker

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-atlas#165]
Split out from https://github.com/18F/cg-product/issues/301.

We're using lots of CI tools: concourse, travis, circle, and wercker. We should get this number down to one or two; let's start by dropping wercker, which we're only using for a few projects. I don't think I have access to wercker. @dlapiduz or @mogul, can you turn off the wercker integration for the following projects:
- [x] cg-docs
- [x] cg-landing
- [x] cg-s3-service-broker

**Comment by jmcarp** [comment]
BTW, we're going to use concourse to check PRs for docs and landing, and we're going to drop our fork of the s3 broker. Concourse PRs at:
- https://github.com/18F/cg-landing/pull/96
- https://github.com/18F/cg-docs/pull/408

**Comment by mogul** [comment]
I killed those three projects in Wercker. It looks like `cg-docs` is still set up for Travis... Is that intentional? Also I notice some stuff is blocking, eg https://github.com/18F/cg-landing/pull/95 ... want to check that out?

**Comment by mogul** [comment]
Also I notice it's got your icon next to the concourse-ci jobs. :) Is there another way to implement this such that it doesn't show these jobs as attached specifically to your account?

**Comment by jmcarp** [comment]
- In what way is cg-docs set up for travis? It's not intended (by my, at least).
- Pull requests made while I was testing this work aren't going to work. If you look at the relevant build, it errored because one of the concourse yaml files wasn't included at the time. Concourse doesn't appear to have an `on_error` callback, so errored builds don't get a status update. In practice, builds that go wrong will fail unless the author does something weird like deleting concourse yaml files.
- The github pullrequest-resource wants an access token with `repo:status` scope. AFAIK, tokens come from a user, so I used mine. We could make a bot account so people don't have to look at my face.

**Comment by afeld** [comment]
While there might be some follow-up tasks, seems like this is done, yeah?

**Comment by mogul** [comment]
I'm still seeing this in the `Integrations and services` for `cg-docs`; something for you to clean up @afeld?
![image](https://cloud.githubusercontent.com/assets/47762/18817577/92b3c3d6-8318-11e6-8ceb-f555c268a2a5.png)
