### ISSUE TITLE
Update PHP buildpack

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-atlas#170]
Based on https://www.us-cert.gov/ncas/bulletins/SB16-263, we need to update to php buildpack >  4.3.18. We can either:
- Upgrade to cf-release 242
- Manually update php buildpack
- [x] Legacy CF Production
- [ ] Legacy CF Staging
- [x] GovCloud CF Production
- [x] GovCloud CF Staging

**Comment by sharms** [comment]
`
curl -L -O https://github.com/cloudfoundry/php-buildpack/releases/download/v4.3.20/php_buildpack-cached-v4.3.20.zip

cf update-buildpack php_buildpack -p ./php_buildpack-cached-v4.3.20.zip`

**Comment by sharms** [comment]
Legacy staging is currently completely unavailable and as such is not exposed.  Rolling out 242 will resolve.
