### ISSUE TITLE
Buildpacks & rootfs(stacks) should be deployable separately from CF release

### ISSUE THREAD

**Issue by LinuxBozo** [18F/cg-atlas#172]
In order to better serve our customers with new buildpack features, and to respond to security updates more quickly, the buildpacks and rootfs should be able to be deployed separately from the main CF release.

**Comment by LinuxBozo** [comment]
rootfs bosh release: 
- http://bosh.io/releases/github.com/cloudfoundry/cflinuxfs2-rootfs-release

Buildpacks are now their own releases, but not listed on bosh.io at the time this comment was made:
- https://github.com/cloudfoundry/ruby-buildpack-release
- https://github.com/cloudfoundry/nodejs-buildpack-release
- https://github.com/cloudfoundry/go-buildpack-release
- https://github.com/cloudfoundry/staticfile-buildpack-release
- https://github.com/cloudfoundry/python-buildpack-release
- https://github.com/cloudfoundry/php-buildpack-release
- https://github.com/cloudfoundry/binary-buildpack-release
- https://github.com/cloudfoundry/java-buildpack-release

**Comment by dlapiduz** [comment]
Can I add this to the list:
- https://github.com/cloudfoundry/dotnet-core-buildpack

**Comment by mogul** [comment]
Looks like this is working!
