### ISSUE TITLE
Automate and document our logsearch restore process

### ISSUE THREAD

**Issue by cnelson** [18F/cg-atlas#179]
In order to be able to quickly restore from backups as an SRE I want an automated, easily scaleable, documented process for restoring specific date ranges of data into elastic search from our s3 backups.

## Acceptance Criteria
- [ ] An automated process exists for restoring data from s3 into elasticsearch

## Implementation Sketch:
Automate the steps describe in this PR https://github.com/18F/cg-site/pull/747 as a bosh job.  See [this slack thread](https://gsa-tts.slack.com/conversation/cloud-gov-atlas/p1485271916005598) for more context.

**Comment by mogul** [comment]
To be broken into two stories by @cnelson, the first of which is `In Progress`

**Comment by cnelson** [comment]
This one edited to reflect the work that should fall out of https://github.com/18F/cg-product/issues/573

https://github.com/18F/cg-atlas/issues/197 opened to to practice a more extreme scenario (which is not critical)

**Comment by cnelson** [comment]
Updated again to reflect the automation work we want to do, but will probably not be done as part of https://github.com/18F/cg-product/issues/573
