### ISSUE TITLE
Configure diego overcommit

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-atlas#185]
We've been talking about overcommitting diego, and we're currently overcommitting memory on staging, but we should do more research before configuring production to overcommit. Some questions to answer:

* Should we overcommit at all?
* If so, by how much?
* How will we get alerted if we overprovision a box and tenant performance start to suffer?

@sharms @cnelson

**Comment by cnelson** [comment]
How much is DEA overcomitted in east?  Probably a good place to start.

**Comment by dlapiduz** [comment]
>Should we overcommit at all?

I think so, most people don't use all the RAM on their apps

> If so, by how much?

10x might be too much but 5x IMO is about right

> How will we get alerted if we overprovision a box and tenant performance start to suffer?

We should get alerts if a box is running out of disk or ram regardless of this so we should get something...
