### ISSUE TITLE
Connect to firehose using client instead of user

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-atlas#192]
So that logsearch firehose credentials don't expire and break everything. This is mostly done--filing the issue for visibility.

* [x] Update go-cfclient
* [x] Update firehose-to-syslog
* [x] Update logsearch-for-cloudfoundry
* [x] Update cg-deploy-logsearch

**Comment by rogeruiz** [comment]
currently blocked on work from 18F/cg-product#496 about UAA not starting up successfully.

**Comment by rogeruiz** [comment]
This is good to go.
