### ISSUE TITLE
Alert when approaching aws resource limits

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-atlas#195]
At the moment, we don't know when we're close to aws resource limits until we hit them, or check (which I'm guessing we don't do very often). We should automate checking so that we can request higher limits before we or our users run into problems.

We might be able to reuse parts of http://docs.aws.amazon.com/solutions/latest/limit-monitor/deployment.html or https://github.com/jantman/awslimitchecker for this.

**Comment by rogeruiz** [comment]
We've got great alerts coming in through Slack now. 

<img width="635" alt="screen shot 2017-01-23 at 11 09 21 am" src="https://cloud.githubusercontent.com/assets/706004/22211904/ada06ee0-e15c-11e6-93a1-77788f87c45d.png">

**Comment by jmcarp** [comment]
We have some more work written up in stories on the new repo, but I think this one can be accepted. Closing.
