### ISSUE TITLE
Ensure S3 access is encrypted

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#21]
In order to minimize the potential to poison our blob store, we want to use encryption with our S3 buckets.

Acceptance Criteria
- [x] The&nbsp;staging and production S3 blob stores use encryption

**Comment by rogeruiz** [comment]
The current work on [cg-encrypt-blobstore-boshrelease](https://github.com/18F/cg-encrypt-blobstore-boshrelease) accepts a single `string` for the bucket name. Which you can see in the [manifest for the `cg-deploy-monitoring` here](https://github.com/18F/cg-deploy-monitoring/blob/3239d4752b66097336bef13f7c24654b6984fe9d/monitoring.yml#L93-L96). The idea for #28 which I closed, is to have this property from the manifest be a list that can be iterated through to encrypt multiple buckets. Something along this example.

``` yaml
bucket: 
- "18f-cf-bucket_one"
- "18f-cf-bucket_two"
# etc...
```

Something that came up during my pairing with @jmcarp was where this list of buckets should come.
1. From the `aws-cli`, meaning we'd ping the server for all available buckets
2. From the `manifest.yml` in the pipeline as a list, _example above_.

That should give some more clarification on #28. I don't think it's technical debt, but rather necessary to get this feature working across all s3 buckets. I hope the explanation above helps with how #28 should be prioritized, feel free to reopen if you think we should split that work out.

**Comment by rogeruiz** [comment]
After speaking to @dlapiduz about how often this script should run, [he mentioned that it should be hourly](https://18f.slack.com/archives/cloud-gov-atlas/p1463761910003279).
