### ISSUE TITLE
SAML IDP delegation for EPA accounts via SecureAuth

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#22]
In order to increase security/compliance and reduce the credentials that users have to manage,&nbsp;@epa.gov users should&nbsp;be authenticated via EPA's&nbsp;SecureAuth&nbsp;service when they reach login.cloud.gov.

Acceptance Criteria
- [x] When a user with an&nbsp;@epa.gov domain attempts to login to cloud.gov, they are authenticated via EPA's SecureAuth&nbsp;service.
- [x] Any considerations about logging in from the command-line (eg reference to using "cf login --sso") are documented in docs.cloud.gov.
- [x] All existing account holders in the&nbsp;@epa.gov domain are notified that they should expect to login via SecureAuth next time, and are referred to the docs.

Implementation notes:&nbsp;
- See Bret&nbsp;for status on request to use EPA's SecureAuth SAML for login

**Comment by cnelson** [comment]
As soon as https://github.com/18F/cg-cf-release/pull/16 is merged, we should be ready to begin testing with the EPA in staging.

-Chris

**Comment by mogul** [comment]
In order to ship this story:
- [x] Update [the](https://docs.cloud.gov/getting-started/accounts/) [three](https://docs.cloud.gov/getting-started/setup/) [docs](https://docs.cloud.gov/ops/managing-users/) to mention the differences in UX between SAML- and non-SAML-accounts
- [x] Turn on the IdP delegation for EPA.gov in UAA's prod config
- [ ] For all existing accounts in EPA.gov, use [`uaapp`](https://github.com/cnelson/uaapp) to: 
  - Flip the account origin to the correct IdP
  - Mail to let them know about the change and point them at the docs

**Comment by mogul** [comment]
@cnelson are we still waiting on EPA to deploy the production config before we can complete this one?

**Comment by cnelson** [comment]
They are waiting on us, but they requested a test with a single user before enabling.  I've been holding off until we figured out how we wanted to handle IDPs in production for now.

I can add them, but if they want to test with a single user I think what we should do is:
- [x] Update the three docs to mention the differences in UX between SAML- and non-SAML-accounts
- [x] Turn on the IdP delegation for EPA.gov in UAA's prod config
- [x] Disable creation of new users from the IdP while testing
- [x] Flip the origin for the designated test user(s) and do validation testing with them.
- [x] Re-enable creation of new users from the IdP
- [ ] For all existing accounts in EPA.gov, use uaapp to flip the origin and notify via email.

Who can we loop in to write the copy for the docs pages, and notification email?

**Comment by mogul** [comment]
Update for anyone not attending stand-ups or in the Slack channel: We've got this working, just waiting for word from the EPA side and then we'll flip all the existing accounts.
