### ISSUE TITLE
[research:4d] Figure out what's involved in redeploying onto GovCloud

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#26]
In order to understand whether&nbsp;a move to GovCloud is a viable short-term path forward, we want to spend up to four days exploring&nbsp;the delta between our hand-propped AWS account and what we'd want&nbsp;automated to feel confident about moving.
- [ ] We feel confident about how to&nbsp;tackle&nbsp;`CGP-287-1` aka `18F/cg-ops#25` (redeploying onto an existing E/W account from scratch).
- [ ] We feel confident we know&nbsp;the&nbsp;gaps we'd encounter moving between AWS E/W and GovCloud, and have enough information to write stories about filling them.

**Comment by cnelson** [comment]
[Groomed story moved to #37 -Bret]

**Comment by cnelson** [comment]
[Groomed story moved to #36 -Bret]

**Comment by cnelson** [comment]
[Groomed story moved to #35 -Bret]

**Comment by cnelson** [comment]
If we end up using Terraform, we'll need to design and document how we store and share state between team members: https://www.terraform.io/docs/state/remote/

**Comment by LinuxBozo** [comment]
[Groomed story moved to #34 -Bret]

**Comment by cnelson** [comment]
The most important thing I learned about CloudFormation vs Terraform this week summed up in a [simple shell script](https://gist.github.com/cnelson/ecdefdeef5d58e0b6766a7f4fa3be9e2)

![image](https://cloud.githubusercontent.com/assets/604163/15271697/3447e1cc-1a0b-11e6-8b5a-ba4cc8eafa56.png)

**Comment by cnelson** [comment]
What we [built last week](https://github.com/18F/cg-provision):

![image](https://cloud.githubusercontent.com/assets/604163/15292199/d00666ac-1b36-11e6-8197-fc826b918660.png)

(source for this document [seq.txt](https://github.com/18F/cg-atlas/files/268827/seq.txt))

**Comment by mogul** [comment]
[Groomed story moved to #33 -Bret]

**Comment by mogul** [comment]
[Groomed story moved to #32 -Bret]

**Comment by mogul** [comment]
[Groomed story moved to #31 -Bret]

**Comment by mogul** [comment]
[Groomed story moved to #30 -Bret]
