### ISSUE TITLE
Dedicated invitations application

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#27]
In order for users who are authenticated by external IdPs to accept invitations, we need a dedicated&nbsp;application that handles the invitation confirmation workflow.

**Acceptance Criteria:**
- [ ] An invitation app functionally equivalent to the branched UAA invitation code exists: Prompt for an e-mail address, and send that user an invitation.
- [ ] Confirmation of an invitation functions properly whether the user's account is local to UAA or gets delegated to an IdP for authentication.

_Note: This is killing tech debt in that we will no longer have to fork upstream UAA to have this functionality, and it is an enabler for confirming invitations with pre-assigned roles._

A test version exists! It's at&nbsp;https://invite.green.18f.gov/

**Comment by mogul** [comment]
[wrong issue -bret]

**Comment by cnelson** [comment]
Working CI pipeline to deploy this app is here: http://ci.cloud.gov/pipelines/deploy-uaa-invite-staging

To prove the origin selection by domain works, I invited two non-existent users: test-proper-origin@gsa.gov, and test-proper-origin@cnelson.org

Checking the accounts with [uaac](http://docs.cloudfoundry.org/adminguide/uaa-user-management.html), I see both have the origin I would expect (gsa for @gsa.gov domains, uaa for unrecognized domains)

```
$ uaac target

Target: https://uaa.green.18f.gov
Context: admin, from client admin

$ uaac user get -a origin 'test-proper-origin@gsa.gov'
  origin: gsa

$ uaac user get -a origin 'test-proper-origin@cnelson.org'
  origin: uaa

```

**Comment by cnelson** [comment]
Your test of going through the GSA auth to create your invited account proves it directly, but to match my tests above, here's the output of uaac for the [test account you created](https://18f.slack.com/archives/cloud-gov-atlas/p1463539466002396):

```
$ uaac target

Target: https://uaa.green.18f.gov
Context: admin, from client admin

$ uaac user get -a origin 'bret.mogilefsky+green@gsa.gov'
  origin: gsa
```

as expected,  the origin was properly set to `gsa`

**Comment by cnelson** [comment]
This is in production: https://invite.cloud.gov/

CI pipeline: http://ci.cloud.gov/pipelines/deploy-uaa-invite-prod
