### ISSUE TITLE
Update s3 encryption to accept an array

### ISSUE THREAD

**Issue by rogeruiz** [18F/cg-atlas#28]
The `cg-encrypt-blobstore-boshrelease` currently only accepts a single bucket at a time. 
- Accept an array to allow `encrypt-blobstore` to monitor more than one s3 bucket

This is a continuation of the work for #21.

**Comment by mogul** [comment]
@rogeruiz can you explain more about why this is needed? I don't have enough context from the description to be able to make decisions about how to prioritize it. Is it just tech debt? Is it an enabler for us to be able to do something else? Are you just noting an idea for how to improve it in future?  Your answers will help me understand whether this belongs in Icebox, or if it stays in Backlog, where it should go in priority.

**Comment by rogeruiz** [comment]
@mogul Sorry for opening this up. I _think_ it should stay part of the #21 story and I just needed a place to put it. I'll close this for now, and add my explanation into #21.
