### ISSUE TITLE
SAML IDP delegation to Azure AD for a single agency

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#3]
[Below, "TLA" refers to a specific three-letter agency. The identity&nbsp;is not particularly sensitive, but since most of our backlog information is public, I'm using "TLA" instead here to preserve their privacy.]

In order to demonstrate that we can provide SSO with agencies who are using Azure Active Directory for their accounts, @tla.gov users should&nbsp;be authenticated via TLA's Azure AD service when they reach login.cloud.gov.

Acceptance Criteria
- [x] When a user with an&nbsp;@tla.gov domain attempts to login to cloud.gov, they are authenticated via TLA's&nbsp;Active Directory service.

Implementation notes including discussion with the TLA in question&nbsp;and pointers to Microsoft docs are in [this Google Groups thread](https://groups.google.com/a/gsa.gov/forum/?hl=en#!topic/cloud-gov-support/EXXk-wdrmpI).

**Comment by cnelson** [comment]
@mogul  We are currently integrating with a client who is using their on-prem ADFS.  Once that is done, can we call this done too or do we still want to test with an actual Azure ADFS instance?

**Comment by mogul** [comment]
I was under the impression previously that on-prem AD didn't support SAML, and the only way to SAML-enable AD was to use Azure ADFS; I didn't even know that there was an on-prem ADFS option! I'm happy to find out if I'm wrong... If the integration happening now is a SAML integration with an agency's AD (whether ADFS or not), rather than using LDAP (which I believe is the case), then yeah, I think we're good.

**Comment by mogul** [comment]
(Just to be clear: I don't want to support the LDAP option for AD integration even though it's technically possible, because it's too insecure and encourages poor practices from the agencies.)

**Comment by cnelson** [comment]
I made the assumption it was on-prem as it's not accessible to the internet at large (doesn't even resolve) but either way, it's def an AD based integration, so I will close this, once we've got them up and running in prod!

**Comment by mogul** [comment]
Waiting until the production IDP metadata is in place.

**Comment by cnelson** [comment]
Now testing in their QA environment, so this is moving along.

**Comment by jbarnicle** [comment]
FDIC is Q/A at the moment - will test when that is complete.

**Comment by cnelson** [comment]
This is in production, will move to closed when the agency confirms working on their end.

**Comment by cnelson** [comment]
Agency confirmed production works as expected, closing this
