### ISSUE TITLE
Ensure Concourse can make use of Terraform to set environments to expected state

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#30]
In order to ensure our environment is in the expected state, As an operations engineers we want our deployments of Concourse to be able to use Terraform
#### Acceptance Criteria
- [ ] Demo that a freshly deployed Concourse can use Terraform-based inputs to set up infrastructure

**Comment by ghost** [comment]
I can take this.

**Comment by LinuxBozo** [comment]
Example pipeline and terraform: https://github.com/LinuxBozo/terraform-example

**Comment by sharms** [comment]
Looks good
