### ISSUE TITLE
Ensure we can use Terraform for AWS provisioning without losing state

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#32]
In order to use Terraform for more reliable (re-)deployments, as ops engineers we need to design and document how we store and share state between Terraform runs. 
#### Acceptance Criteria
- [ ] Concourse can retrieve and store terraform state between builds
#### Implementation Sketch

https://www.terraform.io/docs/state/remote/

**Comment by mogul** [comment]
@LinuxBozo: Want to document how you'd demo this, eg to Madhu, in the AC `???` above? Then move it to Awaiting Acceptance and actually do that. :)

**Comment by LinuxBozo** [comment]
As part of #30 I've rolled it in: 18F/cg-pipeline-tasks#6
Centralized storage provided by pre-provisioned S3 bucket.

Simple example pipeline and terraform manifest here: https://github.com/LinuxBozo/terraform-example

**Comment by sharms** [comment]
Looks good
