### ISSUE TITLE
Make cg-common-resource usable in multiple regions

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#35]
In order to reuse our existing deployment pipeline in other regions. As an operations engineer, I want cg-common-resource to accept a parameter for region.
#### Acceptance Criteria
- [ ] cg-common-resource takes a parameter for the region to operate in
- [ ] The parameter must be a string containing a valid [region code](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html)
#### Implementation Sketch

Fix this: https://github.com/18F/cg-common-resource/blob/master/command.go#L68

**Comment by cnelson** [comment]
This is ready for acceptance.  Here's the working production CI pipeline: 

http://ci.cloud.gov/pipelines/update-cg-common-resource-image
