### ISSUE TITLE
Create a repeatable process for producing a bootstrap concourse image

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#37]
In order to quickly bootstrap a new environment without external dependencies. As an operations engineer I want a pre-configured VM image that runs a standalone concourse instance available for use in our region.
#### Acceptance Criteria
- [x] A single command can be run against a version controlled manifest that creates a Concourse VM image
- [x] A concourse pipeline is running in production that automatically updates this VM image when a new version of Concourse is released.
#### Implementation Sketch

  Use [Packer](https://www.packer.io/) or equivalent tool to build and deploy an AMI with everything we need to deploy a bootstrap pipeline to it.  Prototype: https://github.com/18F/cg-provision/tree/master/bootstrap_concourse/packer

**Comment by cnelson** [comment]
The work for this story will live in [18F/cg-bootstrap-concourse-ami](https://github.com/18F/cg-bootstrap-concourse-ami); the implementation sketch was [discussed in slack](https://18f.slack.com/archives/cloud-gov-atlas/p1463583968002603)

**Comment by cnelson** [comment]
This is ready to be accepted:
- [The single command](https://github.com/18F/cg-bootstrap-concourse-ami#building): `packer build -var-file=secrets.json bootstrap_concourse.json
  `
- [The production pipeline](http://ci.cloud.gov/pipelines/deploy-concourse-ami)

**Comment by sharms** [comment]
Looks good thanks!
