### ISSUE TITLE
SAML IDP delegation for GSA accounts via SecureAuth

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#4]
In order to increase security/compliance and reduce the credentials that users have to manage,&nbsp;@gsa.gov users should&nbsp;be authenticated via GSA's SecureAuth&nbsp;service when they reach login.cloud.gov.

Acceptance Criteria
- [x] When a user with an&nbsp;@gsa.gov domain attempts to login to cloud.gov, they are authenticated via GSA's SecureAuth&nbsp;service.
- [x] Any considerations about logging in from the command-line (eg reference to using "cf login --sso") are documented in docs.cloud.gov.
- [x] All existing account holders in the&nbsp;@gsa.gov domain are notified that they should expect to login via SecureAuth next time, and are referred to the docs.

Implementation notes:&nbsp;
- See Diego for status on request to use&nbsp;GSA's SecureAuth SAML for login

**Comment by cnelson** [comment]
Starting a list of documentation that will need updating:
- [x]  https://docs.cloud.gov/getting-started/accounts/
- [x] https://docs.cloud.gov/getting-started/setup/
- [x] https://docs.cloud.gov/ops/managing-users/

**Comment by mogul** [comment]
In order to ship this story:
- [x] Update [the](https://docs.cloud.gov/getting-started/accounts/) [three](https://docs.cloud.gov/getting-started/setup/) [docs](https://docs.cloud.gov/ops/managing-users/) to mention the differences in UX between SAML- and non-SAML-accounts
- [x] Turn on the IdP delegation for GSA.gov in UAA's prod config
- [x] For all existing accounts in GSA.gov, use [`uaapp`](https://github.com/cnelson/uaapp) to: 
  - Flip the account origin to the correct IdP
  - Mail to let them know about the change and point them at the docs
