### ISSUE TITLE
Travis deployment of dashboard.cloud.gov

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#41]
## Acceptance criteria
- [x] Deploy https://dashboard-master.fr.cloud.gov
- [x] https://dashboard-master.fr.cloud.gov is automatically deployed by Travis on changes to the `master` branch
- [x] https://dashboard.fr.cloud.gov will be automatically deployed by Travis on the next tag

**Comment by afeld** [comment]
[moved up top -bret]

**Comment by mogul** [comment]
Is this all done now? Or is the second checkbox blocked waiting on SSP work?

**Comment by afeld** [comment]
Yep. And it's more of a nuisance to work on while the repository is still private.

/cc @jeremiak @msecret

**Comment by mogul** [comment]
Yep it's done, or yep it's blocked waiting on SSP work?

**Comment by afeld** [comment]
Sorry; I have not worked on the pipeline yet because I am focusing on the SSP.

**Comment by jmcarp** [comment]
@afeld: looks like this got started in https://github.com/18F/cg-deck/blob/concourse/ci/pipeline.yml. I'm assuming I should work off that?

**Comment by msecret** [comment]
The console deployment is going to change this week due to the refactor launch, I suggest we wait for that before we move to concourse, unless it's pressing.

**Comment by jmcarp** [comment]
@msecret: the WIP concourse pipeline is deploying the staging-alpha branch, which iirc is what @afeld deployed manually to console.fr.cloud.gov. If that's the refactor branch, any reason not to finish the pipeline?

**Comment by msecret** [comment]
I guess I'll explain what's changing and you can make the decision on whether we can complete the work, as I'm not 100% sure what the work is to move from travis to concourse:
- We're changing the prod deployment to only be on tags and of the `master` branch. This will deploy to the new `dashboard.cloud.gov` URL.
- We're deploying to `dashboard-staging.cloud.gov` from the `staging` branch.
- We'll probably make a `deprecated` branch for the current console until we phase it out in a week or so.

**Comment by afeld** [comment]
> looks like this got started in https://github.com/18F/cg-deck/blob/concourse/ci/pipeline.yml

Sorry, should have made a work-in-progress pull request!

Just to clarify, that was built to deploy the `staging-alpha` branch to https://console.fr.cloud.gov. Travis is still set up to deploy `master` to https://console.cloud.gov.

**Comment by jmcarp** [comment]
@msecret: https://github.com/18F/cg-deck/pull/406 supports arbitrary branch/tag-based deploy rules, and the example configuration only deploys to prod on tagged commits to `master`. Once we figure out how to get you access to whichever concourse is going to run this job, I'd be happy to show anybody on liberator how this works.

**Comment by msecret** [comment]
Sounds good @jmcarp , I'd be happy to pair with you on it.

**Comment by rogeruiz** [comment]
We're going to keep Travis for deployment for this. We will need to update Travis to deploy this to `govcloud`

**Comment by jcscottiii** [comment]
https://github.com/18F/cg-deck/pull/458 solves this and `Move console app credentials to credential service` issue https://github.com/18F/cg-deck/issues/322

**Comment by jcscottiii** [comment]
Also, need deployer creds for govcloud environment for cg-deck. can be named `cg-deck-deployer`

**Comment by msecret** [comment]
LGTM
