### ISSUE TITLE
Concourse deployment of docker broker

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#42]
## Acceptance criteria
- [x] BOSH manifests for staging and production - https://github.com/18F/cg-deploy-docker-swarm/issues/2
- [x] Concourse pipeline for deploying the manifests - https://github.com/18F/cg-deploy-docker-swarm/issues/3
- [ ] Secrets exist in S3
- [x] Instructions for how to use all of these things

**Comment by afeld** [comment]
Looks like the work is happening in https://github.com/18F/cg-deploy-docker-swarm, so moving to `In Progress`.

**Comment by dlapiduz** [comment]
@afeld I can use some help if you are willing to wrangle yamls

**Comment by mogul** [comment]
Please do go through the [skipped `Grooming` steps](https://github.com/18F/cg-product/blob/master/DeliveryProcess.md#grooming) so we have an idea how we'll know when this is done and how we'll plan to demo it.

**Comment by afeld** [comment]
[migrated to top post -Bret]
@dlapiduz Anything I'm missing?

**Comment by dlapiduz** [comment]
sounds good, let me know if i can help...

**Comment by afeld** [comment]
Moving remaining work to https://github.com/18F/cg-atlas/issues/25#issuecomment-224368518.
