### ISSUE TITLE
Concourse deployment of the S3 broker

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#44]
- [x] Create reusable broker pipeline in Concourse - https://github.com/18F/cg-s3-service-broker/pull/1
- [x] Deploy to production after acceptance tests pass on staging - https://github.com/18F/cg-s3-service-broker/pull/1
- [ ] Deploy to govcloud cf

**Comment by mogul** [comment]
Please retroactively go through the [skipped `Grooming` steps](https://github.com/18F/cg-product/blob/master/DeliveryProcess.md#grooming) so we have an idea how we'll know when this is done and how we'll plan to demo it.

**Comment by afeld** [comment]
Moving remaining work to https://github.com/18F/cg-atlas/issues/25#issuecomment-224368518.
