### ISSUE TITLE
Concourse deployment of the sandbox-bot

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#45]
Getting the `18F/cg-sandbox-bot` from being manually deployed to being deployed on ConcourseCI.
### Acceptance Criteria
- [ ] ~~Getting environmental variables in a :cloud:gov `user-provided-service` 18F/cg-sandbox-bot#4~~
- [x] Create pipeline for deployment of `cg-sandbox-bot` within Concourse using `pipeline.yml`
- [x] Create  / update documentation

**Comment by rogeruiz** [comment]
The `cg-uaa-invite` app is a good example of how the `cg-sandbox-bot` can be modified to deploy through concourse. @jbarnicle 

https://github.com/18F/cg-uaa-invite

**Comment by rogeruiz** [comment]
~~Environment variables in the pipeline don't seem to be set.~~ Nevermind, environmental variables are there using `cf env sandbox-bot`.

**Comment by mogul** [comment]
Closing to have it reflect in burndown
