### ISSUE TITLE
Speed up CI system

### ISSUE THREAD

**Issue by sharms** [18F/cg-atlas#52]
In order for our large team to be effective, we need quicker iteration in our CI pipeline to avoid contention between commits
- [ ] Increase resources from small -> xlarge for acceptance tests
- [ ] Increase parallelism from 2 -> 6

**Comment by sharms** [comment]
Increasing size and moving to parallel execution did not result in measurable speedups

**Comment by mogul** [comment]
We probably need another story at some point to re-attempt to deliver the intended speed benefit here.
