### ISSUE TITLE
Nessus server deployed on GovCloud

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#58]
In order for scanning to be possible in the GovCloud, we need a Nessus scanning master deployed in the GovCloud environment.

**Acceptance Criteria**
- [ ] There's a Nessus manager host deployed in the GovCloud environment, and it's accessible to administrators
- [ ] The Nessus Manager is accessible from all platform hosts via an internal network so that agents can report details

**Implementation Sketch**
- [ ] We going make a BOSH deployment to avoid any stale VM concerns

**Comment by dlapiduz** [comment]
There is a debian package that we can use: https://support.tenable.com/dl_secure.php?x=&y=&z=&p=Nessus-6.7.0-ubuntu1110_amd64.deb

**Comment by frsfx** [comment]
To confirm, is the flow of data nessus scanner agent-->nessus scanning manager-->nessus manager?  Also, can we be provided an account to the Nessus portal?  The debian package is only available to people with a login to their portal.

**Comment by dlapiduz** [comment]
@frsfx it is just nessus agent -> nessus manager. We have the bosh release for the nessus agent but not for the nessus manager. That is what we need.

**Comment by frsfx** [comment]
We are still in the process of scripting the configuration of Nessus Manager.  We hope to have it ready for testing on Monday.

**Comment by ghost** [comment]
Release is at https://github.com/18F/cg-nessus-manager-boshrelease

Note that the final release has not yet been created (`bosh create release`).

**Comment by mogul** [comment]
Automation still needed

**Comment by dlapiduz** [comment]
Because of their way of deploying licenses you can only reuse it once every 10 days… we need to make sure that the bosh deployment stores the license info in the persistent volume rather than in the ephemeral one

**Comment by mogul** [comment]
Pending license purchase for clients, sitting with CAP/@vv

**Comment by dlapiduz** [comment]
Deployed
