### ISSUE TITLE
Create accounts on the staging jump box for Aidan and Josh

### ISSUE THREAD

**Issue by afeld** [18F/cg-atlas#60]
In trying to set up Concourse deployment pipelines for various components, @jmcarp and I would like to be able to try deploying BOSH releases manually to test them. Short of it being easy for us to create our own temporary environments, it would be great to be able to run `bosh` commands from within the staging VPC. Thanks!

**Comment by cnelson** [comment]
@diego had me add my key like so: https://github.com/18F/cloud-cutter/pull/63 to get access to it.  I assume you'll need to do the same.

**Comment by dlapiduz** [comment]
This is ready, right?

**Comment by dlapiduz** [comment]
sorry, "Done"

**Comment by afeld** [comment]
I don't know...how do we try logging into it?

**Comment by mogul** [comment]
Someone needs to write-up any remaining steps and how to login via Concourse.

**Comment by afeld** [comment]
According to @sharms, this is no longer needed, so closing in favor of https://github.com/18F/cg-docs/issues/278.
