### ISSUE TITLE
Deploy Stemcell builder pipeline to e/w

### ISSUE THREAD

**Issue by dlapiduz** [18F/cg-atlas#63]
In order to have parity between the environments and pipelines we need to deploy the stemcell builder job (https://github.com/18F/cg-aws-light-stemcell-builder) to e/w.
### Acceptance Criteria
- [x] Pipeline is created in ci.cloud.gov
- [x] At least one stemcell is uploaded to an S3 bucket in us-east

**Comment by jmcarp** [comment]
Pipeline is running at https://ci.cloud.gov/pipelines/aws-light-stemcell-builder, and stemcells are getting published to the cg-ew-stemcell-builder bucket.

**Comment by mogul** [comment]
Confirmed in use.
