### ISSUE TITLE
Ensure instance types are available in GovCloud

### ISSUE THREAD

**Issue by dlapiduz** [18F/cg-atlas#65]
We currently use instance types that are not available in GovCloud. To prevent issues when redeploying we need to switch instance types in the manifests.
### Acceptance Criteria
- [x] All `cg-deploy-*` repos that reference a bosh deployment include instance types supported by GovCloud

Here is one example of a manifest to change: https://github.com/18F/cg-deploy-cf/blob/staging/cf-infrastructure-aws.yml#L108

**Comment by dlapiduz** [comment]
Instance types supported:

```
t2.nano
t2.micro
t2.small  
t2.medium 
t2.large  
m3.medium 
m3.large  
m3.xlarge 
m3.2xlarge
c3.large  
c3.xlarge 
c3.2xlarge
c3.4xlarge
c3.8xlarge
r3.large  
r3.xlarge 
r3.2xlarge
r3.4xlarge
r3.8xlarge
i2.xlarge 
i2.2xlarge
i2.4xlarge
i2.8xlarge
d2.xlarge 
d2.2xlarge
d2.4xlarge
d2.8xlarge
```

**Comment by jmcarp** [comment]
@madhujoshi and I checked the list of instance types available in e/w but not in gc:

```
{'c4.2xlarge',
 'c4.4xlarge',
 'c4.8xlarge',
 'c4.large',
 'c4.xlarge',
 'g2.2xlarge',
 'g2.8xlarge',
 'm4.10xlarge',
 'm4.2xlarge',
 'm4.4xlarge',
 'm4.large',
 'm4.xlarge',
 'x1.32xlarge'}
```

We filed the PRs above to change c4.\* and m4.\* types to c3.\* and m3.*.

**Comment by dlapiduz** [comment]
closing for now
