### ISSUE TITLE
Add custom SSL negotiation policy to our terraform configuration for our ELBs

### ISSUE THREAD

**Issue by cnelson** [18F/cg-atlas#66]
In order to ensure that our platform is a secure as possible as an SRE I want our ELBs to have their negotiation policies managed by version controlled code so that our platform does not accept possibly insecure SSL connections from misconfigured or adversarial clients.
### Acceptance Critera
- [ ] All ELBs supporting SSL or HTTPS use a custom negotiation policy that matches the current best practice recommendations.
### Implemention Sketch
- Validate this policy is still the current best practice, if it is not then document current best practice.  https://github.com/18F/cg-manifests/blob/0a597f2617d67096b66ded9e6ee007a65f2fb6d3/provisioning/elb.json
- Implement a best practice policy in terraform once this PR has been merged in: https://github.com/hashicorp/terraform/pull/5637

**Comment by mogul** [comment]
What's the blocker and what's the context/priority? Need enough context to decide if this goes in `Icebox` or `Backlog`.

**Comment by cnelson** [comment]
The blocker is that terraform doesn't support scripting ELB SSL negotiation policies yet: https://github.com/hashicorp/terraform/pull/5637 So if we want to do this today, we'd have to do it with a hack like embedding cloudformation in a terraform config, or doing it with a shell script after terraform has run.

Not having this means we don't have the best TLS security we can as we have some older ciphers enabled that we don't want enabled, so I think the priority really comes down to if it's a problem for the auditors or not.  If they demand a fix, we'll do one of the hacks' mentioned above, if not, we should icebox it until terraform adds support at which time this will be a super easy fix.

**Comment by mogul** [comment]
They're almost certain to ask about it; Iceboxing for now, though.

**Comment by jmcarp** [comment]
Now that we're using terraform 0.7.3, this is unblocked for real (the patch adding AWS_LB_SSL_NEGOTIATION_POLICY was included in 0.7.1). Would the idea be to make a reusable module to set ssl negotiation policy for an elb?

**Comment by cnelson** [comment]
Yes, and then apply to all existing ELBs, I can't imagine a case where we'd
want specific TLS negotiation policies for a specific ELB, they should all
be our defined best practice.

-Chris

**Comment by cnelson** [comment]
The GSA IT Security policy references this document for TLS configuration settings: https://insite.gsa.gov/portal/getMediaData?mediaId=669314 but it's dated 2014.  I don't know if there's a more current specification.
