### ISSUE TITLE
Add admin-ui to the staging environment

### ISSUE THREAD

**Issue by cnelson** [18F/cg-atlas#67]
In order to have a staging environment that fully matches production as an SRE I want the admin-ui release to be deployed into the staging environment so that I can be sure that staging accurately reflects production.
## Acceptance Criteria
- [x] cg-deploy-admin-ui is updated to deploy into the staging environment as well as production

**Comment by rogeruiz** [comment]
Ran into the stemcell issue 18F/cg-deploy-admin-ui#8

**Comment by mogul** [comment]
Still needs someone to actually log in and check it.

**Comment by dlapiduz** [comment]
checked! works
