### ISSUE TITLE
Firewall for Nessus

### ISSUE THREAD

**Issue by dlapiduz** [18F/cg-atlas#71]
In order to improve security-in-depth in case the Nessus Manager is compromised, we want to restrict the set of IP address which can access Nessus
- [x] Users on the public internet are unable to connect
- [x] Users on GSA VPN are able to connect
- [x] Configuration is done via Terraform

**Comment by dlapiduz** [comment]
Maybe we can have a (private?) repo that lists IPs and a terraform job in concourse that updates a SG.

**Comment by dlapiduz** [comment]
@LinuxBozo says we should only this for nessus

**Comment by mogul** [comment]
@dlapiduz Is this still necessary? @sharms is saying he thinks the necessary restrictions are already in place.

**Comment by dlapiduz** [comment]
Not in govcloud...

**Comment by mogul** [comment]
Ah, but in E/W? Then I'll leave it prioritized as-is.

**Comment by dlapiduz** [comment]
Just to be clear:
- There is a firewall in E/W
- There is no firewall in GovCloud

**Comment by mogul** [comment]
Okay!

**Comment by sharms** [comment]
https://github.com/18F/cg-provision/pull/40
