### ISSUE TITLE
Review CM controls with 3PAO

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#76]
Review this control set with Veris, using an appointment booked [via the slots on this calendar](https://calendar.google.com/calendar/selfsched?sstoken=UU9UdXpUUXJCRTlwfGRlZmF1bHR8NjAzYTgxMjBkYzQ2OWYxYTk1Y2ExMzkzZWQ2NWNiNWI).

**Acceptance Criteria**
- [ ] Any notes on changes needed in the text is recorded as "docs" in our [followups doc](https://docs.google.com/document/d/1jKVeBO4rodrtpLer0ELtcWccXWV3kxTzTUPgOhsh50g/edit#).
- [ ] Any notes on practices we're missing are recorded as "practices" in our [followups doc](https://docs.google.com/document/d/1jKVeBO4rodrtpLer0ELtcWccXWV3kxTzTUPgOhsh50g/edit#).

**Comment by dlapiduz** [comment]
Done!

**Comment by mogul** [comment]
Per @dlapiduz we need to create a story about a configuration management plan as a remediation for this one before we can close it.

**Comment by rogeruiz** [comment]
@LinuxBozo actively working on this.
