### ISSUE TITLE
Review PL controls with 3PAO

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#80]
Review this control set with Veris, using an appointment booked [via the slots on this calendar](https://calendar.google.com/calendar/selfsched?sstoken=UU9UdXpUUXJCRTlwfGRlZmF1bHR8NjAzYTgxMjBkYzQ2OWYxYTk1Y2ExMzkzZWQ2NWNiNWI).

**Acceptance Criteria**
- [ ] Any notes on changes needed in the text is recorded as "docs" in our [followups doc](https://docs.google.com/document/d/1jKVeBO4rodrtpLer0ELtcWccXWV3kxTzTUPgOhsh50g/edit#).
- [ ] Any notes on practices we're missing are recorded as "practices" in our [followups doc](https://docs.google.com/document/d/1jKVeBO4rodrtpLer0ELtcWccXWV3kxTzTUPgOhsh50g/edit#).

**Comment by mogul** [comment]
There was a mix-up and I ended up meeting with Veris about PL even though it's not done yet... I [left some feedback](https://github.com/18F/cg-compliance/issues/80#issuecomment-225971501) on the issue about filling in the PL controls. I'm putting this card back into the `Backlog` because it's almost certain that we'll want to review this one again.

**Comment by dlapiduz** [comment]
Going to close this because there isn't going to be a new PL session, they are just going to review the SSP.
