### ISSUE TITLE
GovCloud Asset Review / Security Scan

### ISSUE THREAD

**Issue by sharms** [18F/cg-atlas#86]
Working with Matt from Veris

**Comment by mogul** [comment]
Can you edit the post at the top to elaborate what's in scope here, what the intended outcome will be, and what we'll have to show for it? Also should this be In Progress?

**Comment by mogul** [comment]
@sharms _ping_ can you tell us what this is about?

**Comment by sharms** [comment]
Worked with Matt Chaiko from Veris to work through security scanning and demonstrate those scans with a external party present.  I have sent the final results to Matt so unless I hear anything back this can be closed.

**Comment by afeld** [comment]
Keeping this open- still working with Matt, but this should be all done tomorrow.

**Comment by afeld** [comment]
- [x] https://admin.fr.cloud.gov/ ?
- [x] https://api.fr.cloud.gov/
- [x] https://ci.fr.cloud.gov/
- [x] https://community.fr.cloud.gov/
- [x] https://console.fr.cloud.gov/ (needs AJAX spidering)
- [x] https://docs.fr.cloud.gov/
- [x] https://invite.fr.cloud.gov/
- [x] https://landing.fr.cloud.gov/
- [x] https://login.fr.cloud.gov/
- [x] https://logs.fr.cloud.gov/
- [x] https://metrics.fr.cloud.gov/

**Comment by afeld** [comment]
Results uploaded to [Google Drive](https://drive.google.com/a/gsa.gov/folderview?id=0B5fn0WMJaYDnaFdCak5WNWRGb1U&usp=sharing) and sent to Matt.
