### ISSUE TITLE
Lock down access to allowed_keys for jumpbox

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#9]
In order to tightly control which SSH allowed_keys are on jumpboxes, the jumpbox configuration should come from&nbsp;a repository with write access restricted to only cloud.gov admins.

Acceptance Criteria
- [ ] Elements affecting jumpbox configuration for cloud.gov move to a separate repository
- [ ] Only `cloud-gov-ops` can write to that repository

**Comment by dlapiduz** [comment]
Should we close this since there are no more jumpboxes?

**Comment by mogul** [comment]
Closing as there's no jumpbox in AWS GovCloud. (There still are in the E/W deployment, but we'll be dusting off of that soon and it's not in the assessment boundary.)
