### ISSUE TITLE
RIR-A: Practice IR plan with tabletop exercise

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#92]
In order to get the team familiar with [our new Incident Response Plan](https://docs.cloud.gov/ops/security-ir/) ensure we're able to follow it well-enough to satisfy compliance requirements, and identify potential improvements, we should run a tabletop exercise with @kimberbat and @jacobian.

**Acceptance criteria**
- [x] We document the results of a tabletop exercise of our IRP involving everyone regularly working on the Atlas stream (may be multiple events to avoid too-large meetings and test our ability to operate without everyone present)
- [x] The team calendar includes a yearly recurrence of a training meeting and tabletop exercise

**Implementation sketch**
- [x] Schedule a meeting with the whole team to review the IRP and accompanying checklist, and answer questions/make edits as needed. Make sure the calendar invite is in the cloud.gov calendar, and recurs yearly.
- [x] Schedule one (or more) meetings to run the tabletop exercise. Make sure the calendar invite is in the cloud.gov calendar, and recurs yearly.
- [ ] Document the results
- [x] Post the recordings

**Comment by mogul** [comment]
@kimberbat @jacobian if we can possibly get through this with the team before next Friday we can avoid having to account for it in the FedRAMP SAR and POA&M... Do you think it's possible? If so can you schedule the meetings?

**Comment by jacobian** [comment]
@mogul I can make this happen next week. It'll be a bit rough and rushed -- call it a "beta test" of our training :) -- but I can make it happen. I'm not sure who needs to be involved, or their schedules, so can you take care of scheduling some time with the appropriate team member(s) and I? I don't have anything on my calendar that can't be moved, so feel free to schedule whenever. I think we should go with a 60 minute review session, and a 90 minute exercise session a day or two later (to give time to make edits if needed).

**Comment by mogul** [comment]
A beta test is fine... It'll always be a work in progress anyway, right? :) I scheduled meetings for next Thursday and Friday on the cloud.gov calendar. 

/cc @18F/cloud-gov-ops

**Comment by mogul** [comment]
The tabletop/roleplay exercise has been completed! Notes from both the training and the exercise are here:
https://docs.google.com/document/d/1VpO04KLFLY66Mfv6Wklf-KUQJW03mX3f29XfsR5_mYY/edit#heading=h.wcm2izxfr8kd

**Comment by mogul** [comment]
@afeld: Can you list the set of people who attended each of the two meetings by referring to the recording? And can you place a link to the recording (in Drive) here?

**Comment by afeld** [comment]
Training attendees:
- @afeld
- @brittag 
- @jacobian 
- @jbarnicle 
- @kimberbat 
- @LinuxBozo 
- @mogul 
- @rogeruiz 
- @thisisdano 

Exercise attendees:
- @afeld
- @brittag 
- @dlapiduz
- @jacobian 
- @jbarnicle 
- @jmcarp 
- @kimberbat 
- @LinuxBozo 
- @mogul 
- @rogeruiz 
- @sharms 

Will upload the recordings and post the links here soon.

**Comment by afeld** [comment]
Uploaded the video of the [training](https://drive.google.com/open?id=0B5fn0WMJaYDnX3BDMTQ3SDA2c2s) and the [exercise](https://drive.google.com/open?id=0B5fn0WMJaYDnRUJuVWxRUDRVQmM). Anything formal need to be done around the `Document the results` task, or are the videos and the notes doc sufficient to close this?

**Comment by jacobian** [comment]
I can write a brief report if it's needed. LMK if you need me to do that.

**Comment by dlapiduz** [comment]
@jacobian I'd love a non official debrief of what things we got wrong and what we can improve...

**Comment by afeld** [comment]
Anything official that's still required? @clovett3 do you know?
