### ISSUE TITLE
Make Concourse Intercepts great again

### ISSUE THREAD

**Issue by sharms** [18F/cg-atlas#97]
As the cloud.gov team, we need to be able to use temporary containers to do troubleshooting of bosh deployments
- [x] A concourse job can be run that provides a temporary container that can be intercepted with BOSH cli access

**Comment by afeld** [comment]
> Create Concourse pipeline to update https://hub.docker.com/r/18fgsa/bosh-deployment-resource/

Is that preferable to using the [Docker Hub Automated Builds](https://docs.docker.com/docker-hub/builds/)?

**Comment by LinuxBozo** [comment]
https://ci.fr.cloud.gov/pipelines/jumpbox
