### ISSUE TITLE
Document third-party service integrations

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#98]
In order to ensure cloud.gov's 90-day GSA LATO is extended, the cloud.gov team must address GSA ISSO concerns about integrations with third-party services by July 21st.  

**Acceptance Criteria**   
- [ ] Identify each third-party service cloud.gov uses.  
- [ ] For each service, describe what data is stored, how connections are secured, how it is accessed, etc  
- [ ] Submit the information for GSA ISSO approval

**Comment by mogul** [comment]
@clovett3 referred to an existing document here... 
https://github.com/18F/cg-atlas/issues/29#issuecomment-230524116

It looks like it still needs eyes and editing.

**Comment by mogul** [comment]
Do we still need this @dlapiduz? I thought so...

**Comment by mogul** [comment]
Or is this a dupe of 18F/cg-compliance#162?

**Comment by brittag** [comment]
We now have a [services table](https://docs.google.com/document/d/1xZI6mTbJpXVG90rGL1LswgPf6YUN7FM2yBPhfPhRgw8/edit#) that should fulfill this requirement if we need this for anything in the future.
