### ISSUE TITLE
Fix logs on staging

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-atlas#99]
I noticed that CF logs on staging aren't working--running `cf logs` fails with the following:

> Warning: error tailing logs
> Error dialing traffic controller server: x509: certificate is valid for *.green.18f.gov, green.18f.gov, not doppler.sys.green.18f.gov.
> Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is wss://doppler.sys.green.18f.gov:4443).

From @sharms via slack:

> We will need to ask in #infrastructure to get a new certificate for `*.sys.green.18f.gov` - it appears `*.*.green.18f.gov` may not work across all clients as RFC 2818 / 6125 support varies
> and prior to that, we should probably just figure out if *.sys.staging.cloud.gov should be the real name and point to GovCloud

**Comment by dlapiduz** [comment]
Created a wildcard cert with a couple more domains on it... should be good now
